import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import '@ant-design/v5-patch-for-react-19';
import { ThemeProvider } from 'features/ToggleTheme';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

const muller = localFont({
	src: [
		{
			path: 'fonts/MullerRegular.woff2',
			weight: '400',
			style: 'normal',
		},
		{
			path: 'fonts/MullerLight.woff2',
			weight: '300',
			style: 'normal',
		},
		{
			path: 'fonts/MullerMedium.woff2',
			weight: '500',
			style: 'normal',
		},
	],
	display: 'swap',
	variable: '--font-muller',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ThemeProvider>
			<html lang='ru'>
				<body
					className={`${geistSans.variable} ${geistMono.variable} ${muller.variable} gradient font-muller text-mainColor *:border-mainColor/40 *:bg-mainColorRevers/60 *:dark:bg-mainColorRevers/40 container mx-auto flex min-h-[100dvh] flex-col gap-5 p-4 font-normal antialiased *:rounded-3xl *:px-4`}>
					<AntdRegistry>{children}</AntdRegistry>
				</body>
			</html>
		</ThemeProvider>
	);
}
